spring:
  profiles:
    include:
      - gcp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: ${MONGO_AUTH_DB}
      database: ${MONGO_DB}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
