spring:
  profiles:
    include:
      - gcp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_AUTH_DB}}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
